[package]
name = "draft-claw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-graphics = "0.22.3"
core-foundation = "0.9.3"
leptess = "0.14.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
image = "0.24.6"
imageproc = "0.23.0"
opencv = "0.80.0"
surrealdb = "1.0.0-beta.9"
tokio = { version = "1.28.0", features = ["macros"] }
dotenv = "0.15.0"
strsim = "0.10.0"
serenity = { version = "0.11.5", default_features = false, features = ["rustls_backend", "client", "gateway", "model"] }
