[package]
name = "draft-claw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-graphics = "0.22.3"
core-foundation = "0.9.1"
leptess = "0.14.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
