[package]
name = "draft-claw"
version = "0.1.0"
edition = "2021"

[features]
default = ["bot"]
capture = []
bot = []

[dependencies]
core-graphics = "0.22.3"
core-foundation = "0.9.3"
leptess = "0.14.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
image = "0.24.6"
imageproc = "0.23.0"
opencv = "0.80.0"
surrealdb = { version = "1.0.0-beta.9+20230402", features = ["http", "protocol-http"] }
tokio = { version = "1.28.0", features = ["macros", "signal"] }
dotenv = "0.15.0"
strsim = "0.10.0"
serenity = { version = "0.11.5", default_features = false, features = ["rustls_backend", "client", "gateway", "model"] }
clap = { version = "4.2.5", features = ["cargo"] }
shlex = "1.1.0"
tempfile = "3.5.0"
directories = "5.0.1"
nanoid = "0.4.0"
regex = "1.8.1"
indicium = "0.4.3"
lazy_static = "1.4.0"
shuttle-runtime = "0.15.0"
anyhow = "1.0.71"
shuttle-secrets = "0.15.0"
shuttle-serenity = "0.15.0"
tracing = "0.1.37"
