# fly.toml app configuration file generated for draft-claw-bot on 2023-05-06T00:41:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "draft-claw-bot"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
